---
- hosts: workers
  become: yes
  vars:
    frontend_dns: hiteam.com
    backend_dns: backend.com  
    keycloak_dns: keycloak.com
    billing_dns: billing.com
    frontendport: 30001
    backendport: 30002
    keycloakport: 30003
    billingport: 30004
    
  tasks: 
  - name: Installing epel
    yum:
      name: epel-release
      state: latest

  - name: nginx is present
    yum:
      name: nginx
      state: latest

  - name: Save nginx.conf
    template: 
      src: nginx.conf.j2 
      dest: "/etc/nginx/nginx.conf"
      mode: 0644
      force: yes
  
  - name: Creates directory
    file:
      path: /etc/nginx/conf.d/sites-enabled
      state: directory

  - name: Save server conf
    template: 
      src: server.conf.j2 
      dest: "/etc/nginx/conf.d/sites-enabled/{{ item.dns }}.conf" 
      mode: 0644
      force: yes
    with_items:
       - { dns: "{{ frontend_dns }}", port: "{{ frontendport }}" , stream: "{{ frontend_dns }}" }
       - { dns: "{{ backend_dns }}" , port: "{{ backendport }}" , stream: "{{ backend_dns }}" }
       - { dns: "{{ keycloak_dns }}" ,port: "{{ keycloakport }}" , stream: "{{ keycloak_dns }}" }
       - { dns: "{{ billing_dns }}" ,port: "{{ billingport }}" , stream: "{{ billing_dns }}" }

  - name: Creates directory
    file:
      path: /etc/nginx/conf.d/sites-enabled/{{ item.stream }}.d
      state: directory
    with_items:
      - { dns: "{{ frontend_dns }}" , stream: "{{ frontend_dns }}" }
      - { dns: "{{ backend_dns }}" , stream: "{{ backend_dns }}" }
      - { dns: "{{ keycloak_dns }}" , stream: "{{ keycloak_dns }}" }
      - { dns: "{{ billing_dns }}" , stream: "{{ billing_dns }}" }


  - name: Save server conf
    template:
      src: main.conf.j2
      dest: "/etc/nginx/conf.d/sites-enabled/{{ item.stream }}.d/main.conf"
      mode: 0644
      force: yes
    with_items:
       - { dns: "{{ frontend_dns }}" , stream: "{{ frontend_dns }}" }
       - { dns: "{{ backend_dns }}" , stream: "{{ backend_dns }}" }
       - { dns: "{{ billing_dns }}" , stream: "{{ billing_dns }}" }
       
  - name: Save keycloak conf
    template:
      src: keycloak.conf.j2
      dest: "/etc/nginx/conf.d/sites-enabled/{{ item.stream }}.d/main.conf"
      mode: 0644
      force: yes
    with_items:
       - { dns: "{{ keycloak_dns }}" , stream: "{{ keycloak_dns }}" }  
  

  - name: nginx -t to check the conf file syntax
    command: "nginx -t"
    notify:
      - restart nginx

  handlers:

  - name: restart nginx
    service: name=nginx state=restarted

