apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  labels:
    app: keycloak
data:
  KEYCLOAK_USER: admin
  KEYCLOAK_PASSWORD: publPh6cHuthEbRApHeN
  DB_ADDR: keycloak-postgres
  DB_PORT: "5432"
  DB_DATABASE: keycloak
  DB_USER: keycloak
  DB_PASSWORD: password
  DB_VENDOR: postgres
  PROXY_ADDRESS_FORWARDING: "true"
  realmName: master
  adminName: admin
  adminPassword: publPh6cHuthEbRApHeN
  adminClientId: admin-cli
  keycloakAccessEndpoint: /protocol/openid-connect/token

