---
- hosts: all
  vars:
    nexus_user: {}      #dummy user
    nexus_pwd: {}   #dummy pwd
    nexus_ip: {}
    nexus_docker_port: 8086  #dummy port
  
  tasks:
  - name: update apt packages
    apt: update_cache=yes cache_valid_time=3600
    sudo: true

  - name: Install docker
    command: apt-get -y install docker.io
    register: docker_log
    sudo: true
  - name: Copy the docker.json
    copy: 
      src: ./daemon.json
      dest: /etc/docker/
    sudo: true
  - name: Add user to docker group
    command: usermod -a -G docker ubuntu
    sudo: true
  - name: restart docker
    sudo: true
    service:
       name: docker
       state: restarted

  - name: Login to the nexus Artifactory
    command: docker login -u {{nexus_user}} -p {{nexus_pwd}} {{nexus_ip}}:{{nexus_docker_port}}

  - name: update the cache
    apt: update_cache=yes cache_valid_time=3600
    sudo: true 

  

