---
- hosts: nexus
  sudo: true
  vars:
    nexus_version: latest  
    nexus_download_url: https://download.sonatype.com/nexus/3/{{nexus_version}}-unix.tar.gz
    #nexus_download_url: http://www.sonatype.org/downloads/nexus-{{nexus_version}}-bundle.tar.gz
    nexus_download_dest: /tmp/nexus-{{nexus_version}}-unix.tar.gz
    nexus_extracted_dir: /tmp/nexus_extracted_dir
    nexus_dir: /opt/nexus
    nexus_root: /opt

  tasks:

          #- name: update yum repo
          #yum: 
          #update_cache: true
          #sudo: true

  - name: install wget
    yum: 
     name: wget  
     state: present
     update_cache: true

  - name: Installing java 8
    command: yum install -y java-1.8.0-openjdk-devel

  - name: create "nexus" group
    group: name=nexus 
    sudo: true

  - name: create "nexus" user
    user: name=nexus group=nexus 
    sudo: true

  - name: download nexus
    get_url: url={{nexus_download_url}} dest={{nexus_download_dest}}
    register: nexus_download

  - name: create {{nexus_extracted_dir}} directory
    file: path={{nexus_extracted_dir}} state=directory
    when: nexus_download.changed
    sudo: true

  - name: extract nexus to {{nexus_extracted_dir}}
    command: tar xzf {{nexus_download_dest}} -C {{nexus_extracted_dir}} --strip-components=1
    when: nexus_download.changed
    sudo: true

  - name: move nexus to {{nexus_dir}} directory
    command: cp -a {{nexus_extracted_dir}}/. {{nexus_dir}}
    when: nexus_download.changed
    sudo: true

  - name: remove {{nexus_extracted_dir}} directory
    command: rm -rf {{nexus_extracted_dir}}
    when: nexus_download.changed
    sudo: true

  - name: make {{nexus_root}} directory property of "nexus" user/group
    file: path={{nexus_root}} group=nexus owner=nexus recurse=true
    sudo: true

  - name: make nexus runned by "nexus" user
    lineinfile: dest={{nexus_dir}}/bin/nexus.rc regexp="#run_as_user=" line="run_as_user=nexus" backrefs=true
    sudo: true

  - name: set NEXUS_HOME
    lineinfile: dest={{nexus_dir}}/bin/nexus regexp="^NEXUS_HOME" line="NEXUS_HOME={{nexus_dir}}" backrefs=true
    sudo: true

  - name: create nexus piddir
    file: path=/var/run/nexus state=directory group=nexus owner=nexus
    sudo: true

  - name: set nexus pidir
    lineinfile: dest={{nexus_dir}}/bin/nexus regexp="^#PIDDIR=" line="PIDDIR=/var/run/nexus" backrefs=true
    sudo: true

  - name: create symbolic links to /etc/init.d/nexus
    file: src={{nexus_dir}}/bin/nexus dest=/etc/init.d/nexus state=link
    sudo: true

  - name: configure runlevel links for nexus
    command: chkconfig --add nexus
    command: chkconfig --levels 345 nexus on
    sudo: true
    
  - name: start nexus
    service: name=nexus state=started pattern={{nexus_dir}}
    sudo: true
