apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: 165.22.121.164:8086/onboard_backend:1.2.1
        name: backend
        envFrom:
           - configMapRef:
                name: backend-config
           - configMapRef:
                name: backendurl-config
     
        ports:
        - containerPort: 8443
      imagePullSecrets:
         - name: dockersecrete
