apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: 134.209.29.42:8086/onboard_frontend:1.2.79
        name: frontend
        envFrom:
           - configMapRef:
                name: frontend-config
               
        ports:
        - containerPort: 3000
      imagePullSecrets:
         - name: dockersecrete

