---
- hosts: workers
  become: yes
  vars:
    frontend_dns: hiteam.com
    cert_email: vikyranga@gmail.com
  
  tasks: 
  - name: Installing epel
    yum:
      name: epel-release
      state: latest

  
  - name: Install letsencrypt dependencies
    yum:
      name: certbot-nginx
      state: latest
      update_cache: yes

  - name: SSL certs generation
    command: "certbot --installer nginx --authenticator standalone --agree-tos --email {{ cert_email }} certonly -n -d {{ item }} --pre-hook 'service nginx stop' --post-hook 'service nginx start'"
    args:
      creates: "/etc/letsencrypt/live/{{ item }}"
    with_items:
     - "{{ frontend_dns }}"

