---
- hosts: jenkins
  
  tasks:
    - name: Installing java8
      command: yum install -y java-1.8.0-openjdk-devel
      sudo: true

    - name: Ensure Jenkins Repository is Installed
      yum_repository:
        name: jenkins
        state: present
        description: Official Jenkins Yum Repo
        baseurl: http://pkg.jenkins.io/redhat
        gpgkey: https://jenkins-ci.org/redhat/jenkins-ci.org.key
        gpgcheck: yes
        enabled: yes

    - name: Ensure Jenkins is Installed
      yum :
        name: jenkins
        update_cache: yes
        state: present

    - name: Enable and Start the Jenkins Service
      service:
        name: jenkins
        enabled: yes
        state: started
      sudo: true

    - name: Installing Wget for JQ
      shell: yum install -y wget

    - name: Installing the JQ
      shell: wget http://download-ib01.fedoraproject.org/pub/epel/7/x86_64/ && yum install -y jq

    - name: "Installing Docker Prerequisite packages"
      yum:
       name: "{{ item }}"
       state: latest
      with_items:
       - yum-utils
       - device-mapper-persistent-data
       - lvm2

    - name: "Configuring docker-ce repo"
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0644

    - name: "Installing Docker latest version"
      yum:
       name: docker-ce
       state: present

    - name: "Starting and Enabling Docker service"
      service:
        name: docker
        state: started
        enabled: yes
