pipeline {
    agent any

    parameters {
        string(name: 'Master_ip' , defaultValue: "", description: 'Master Ip address')
        string(name: 'Worker_ip' , defaultValue: "", description: 'Worker Ip address')
        password(name: 'Master_pass' , defaultValue: "", description: 'Master passowrd')
        password(name: 'Worker_pass' , defaultValue: "", description: "worker Passowrd")

    }

    stages {
       stage(" Creating a inventory File") {
         steps{
                sh ''' cd Centos/Ansible_Kubernetes
                       chmod +x test.sh'''
                 sh """ set +x 
                       Centos/Ansible_Kubernetes/test.sh ${params.Master_ip} ${params.Master_pass} ${params.Worker_ip} ${params.Worker_pass}
                       """
                       
         }
       }
       stage("Kubernets Installation"){
         steps{
             sh ''' cd Centos/Ansible_Kubernetes
                    export ANSIBLE_HOST_KEY_CHECKING=False
                    ansible-playbook -i inventory kube.yml '''
             sh 'sleep 5' 
         }
       }  
    stage("Docker installation"){
        steps{
            sh 'sleep 10'
            sh ''' cd Centos/Ansible_Kubernetes
                   set +x
                   export ANSIBLE_HOST_KEY_CHECKING=False
                   ansible-playbook -i inventory docker.yml --extra-vars "nexus_user=CC_devops nexus_pwd=3RiNO#A_ nexus_ip=134.209.29.42 nexus_docker_port=8086"
               '''
        }
      }
    }
}
