apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: billing
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
      - image: 165.22.121.164:8086/onboard_billing:1.2.1
        name: billing
        envFrom:
           - configMapRef:
                name: billing-config
           - configMapRef:
                name: billingurl-config               
        ports:
        - containerPort: 3001
      imagePullSecrets:
         - name: dockersecrete
