apiVersion: v1
kind: Service
metadata:
  name: elasticsearchbackend
spec:
  ports:
    - port: 4000
      #targetPort: 2000
      nodePort: 30012
  type: NodePort
  selector:
    app: elasticsearchbackend
