apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
    - port: 9200
      protocol: TCP
      #targetPort: 9200
      nodePort: 30011
  type: NodePort
  selector:
    app: elasticsearch
