apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 3001
      protocol: TCP
      #targetPort: 3001
      nodePort: 30008
  type: NodePort
  selector:
    app: frontend
