apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  ports:
    - port: 8080
      protocol: TCP
      #targetPort: 9990
      nodePort: 30010
  type: NodePort
  selector:
    app: keycloak
