apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - image: 178.62.64.11:8086/platform_keycloak:1.2.4
        name: keycloak
        envFrom:
           - configMapRef:
               name: keycloak-config     

        ports:
        - containerPort: 8080
      imagePullSecrets:
         - name: dockersecrete

